- name: Launch an EC2 instance
  hosts: localhost
  collections:
    - amazon.aws
  tasks:

  - name: Create security group
    amazon.aws.ec2_security_group:
      name: "new-security-group"
      description: "Sec group for app"
      rules:                               
        - proto: tcp
          ports:
            - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on ssh port
      state: present
    delegate_to: localhost      